// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive.dart';
import 'package:sample_chat/models/streamio_auth_token.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(StreamIOAuthTokenAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(StreamIOAuthTokenAdapter());
  }
}
